### ISSUE TITLE
Miscalculation in uncalled function?

### ISSUE THREAD

**Issue by yuichiok** [SiWECAL-TestBeam/SiWECAL-TB-monitoring#18]
Hi all,

In a `build_events.py` below
https://github.com/kunathj/SiWECAL-TB-analysis/blob/1f56c2788a2d95f95724a8120515ff1076d78319/eventbuilding/build_events.py#L392-L399
I see the the line says `energy =  (adc - pedestal) + mip`
This is definitely a mistake, no?
Even though it seems it's not being called at the default setting.

**Comment by kunathj** [comment]
Sorry for the late response! It is definitely a mistake (should be `energy = (adc - pedestal) / mip` of course). We should fix this directly in https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis.
Do you want to commit the fix, or should I? When it is fixed, I can change the monitoring to use the updated SiWECAL-TB-analysis.

But it is also true that this is not an issue in the standard use case, so we can keep all build.root files.

**Comment by kunathj** [comment]
Will be fixed by https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/pull/44.
